pub mod handler_register;
mod auth_handler;
mod health_handler;
mod item_handler;
mod user_handler;
mod saved_item_handler;
mod chat_handler;
mod image_upload_handler;
mod openai_handler;
mod item_search_handler;