apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-core-deployment
  labels:
    app: backend-core
spec:
  selector:
    matchLabels:
      app: backend-core
  template:
    metadata:
      labels:
        app: backend-core
    spec:
      containers:
        - name: backend-core
          image: wry0313/renu:latest
          envFrom:
          - configMapRef:
              name: backend-core-config