apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-core-deployment
  labels:
    app: db-core
spec:
  selector:
    matchLabels: # the deployment will manage pods whose labels match this selector
      app: db-core
  template: # the deployment will create pods from this template
    metadata:
      labels:
        app: db-core
    spec:
      containers: # the pkuod will run a container from this image
        - name: db-core
          image: paradedb/paradedb:latest
          # image: postgres:latest
          volumeMounts:
            - name: db-core-persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
          - name: PGDATA
            value: /var/lib/postgresql/mydata
          - name: POSTGRES_DB
            value: "renu-db"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
      volumes:
        - name: db-core-persistent-storage
          persistentVolumeClaim:
            claimName: db-core-pvc