apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-core-deployment
  labels:
    app: db-core
spec:
  revisionHistoryLimit: 0 # keep one replica set
  selector:
    matchLabels: # the deployment will manage pods whose labels match this selector
      app: db-core
  template: # the deployment will create pods from this template
    metadata:
      labels:
        app: db-core
    spec:
      containers: # the pod will run a container from this image
        - name: db-core
          image: paradedb/paradedb:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - name: db-core-persistent-storage
              mountPath: /var/lib/postgresql/data/renu-data
          # env:
          #   - name: PGDATA
          #     value: /var/lib/postgresql/renu-data
          envFrom:
          - configMapRef:
              name: db-core-config
          - secretRef:
              name: db-core-secret
      volumes:
        - name: db-core-persistent-storage
          persistentVolumeClaim:
            claimName: db-core-pvc
