# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-core
# spec:
#   selector:
#     app: backend-core
#   ports:
#     - name: backend-core-port
#       port: 8080
#       nodePort: 30100
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: backend-core
spec:
  selector:
    app: backend-core
  ports:
    - name: backend-core-port
      port: 80
      targetPort: 8080
  type: LoadBalancer
