name: Rust CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.DROPLET_PASSPdoHRASE }}
        script: |
          docker pull wry0313/marketplace:latest
          docker stop marketplace-container || true
          docker rm marketplace-container || true
          docker run --name marketplace-container -p 8080:8080 wry0313/marketplace:latest
